### ISSUE TITLE
Feature: Calculate stock with fixed price and no costs

### ISSUE THREAD

**Issue by tk-wobb** [sah-comp/wobb#32]
There might be a new permament requirement that certain stock of a (sub)-deliverer have to be calculated with a fixed price as well as not being charged costs.

**Comment by sah-comp** [comment]
Another requirement is that the stock has to be separated into a stand-alone deliverer and invoice.

**Comment by sah-comp** [comment]
There will not be a feature for now. The requirement was solved by adding a Pricing record that has only optimal range settings for MFA and weight in combination with an _alias_-Deliverer which does not subtract costs.
